# Generated by Django 3.2.3 on 2022-10-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='spotify_playlist_cover/')),
                ('playlist_id', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(default='TYPE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyPlaylistTracksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cover', models.ImageField(upload_to='spotify_playlist_tracks_cover')),
                ('artist', models.CharField(max_length=200)),
                ('track_id', models.CharField(max_length=200)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('refresh_token', models.CharField(max_length=300)),
                ('expires_in', models.DateTimeField(max_length=300)),
                ('token_type', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
