# Generated by Django 3.2.3 on 2022-05-04 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('playlist_id', models.CharField(max_length=200)),
                ('uri', models.URLField()),
                ('type', models.CharField(default='TYPE', max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='spotify_playlist_cover/')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyPlaylistTracksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cover', models.ImageField(upload_to='spotify_playlist_tracks_cover')),
                ('artist', models.CharField(max_length=200)),
                ('track_id', models.CharField(max_length=200)),
                ('uri', models.URLField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.spotifyplaylistmodel')),
            ],
        ),
        migrations.AddField(
            model_name='spotifyplaylistmodel',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.spotifyplaylisttracksmodel'),
        ),
    ]
