# Generated by Django 3.2.3 on 2022-10-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotifyplaylisttracksmodel',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.spotifyplaylistmodel'),
        ),
        migrations.AddField(
            model_name='spotifyplaylistmodel',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_api.spotifyplaylisttracksmodel'),
        ),
        migrations.AddField(
            model_name='spotifyplaylistmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
