# Generated by Django 3.2.3 on 2023-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='spotify_username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
