# Generated by Django 3.2.3 on 2022-05-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0006_auto_20220524_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyplaylistmodel',
            old_name='uri',
            new_name='url',
        ),
    ]
