# Generated by Django 3.2.3 on 2022-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(verbose_name=((1, 'Like'), (2, 'Comment'), (3, 'Follow')))),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
