# Generated by Django 3.2.3 on 2022-12-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
