# Generated by Django 3.2.3 on 2023-01-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20230110_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
