# Generated by Django 3.2.3 on 2023-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/notif_images'),
        ),
    ]
