# Generated by Django 3.2.3 on 2023-01-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='playlist_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
