# Generated by Django 3.2.3 on 2022-10-18 21:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=1000, null=True), blank=True, default=None, null=True, size=None)),
                ('description', models.TextField(default=None)),
                ('playlist_url', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_ApiURL', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_id', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_cover', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_title', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_type', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_uri', models.CharField(blank=True, default=None, max_length=300)),
                ('playlist_tracks', models.CharField(blank=True, default=None, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.comment')),
            ],
        ),
    ]
