# Generated by Django 3.2.3 on 2022-06-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='spotify_playlist',
        ),
    ]
