# Generated by Django 3.2.3 on 2022-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_playlist_spotify_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
    ]
