# Generated by Django 3.2.3 on 2022-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_playlist_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='images',
            field=models.FileField(blank=True, default=None, max_length=3000, null=True, upload_to='media/playlist_images'),
        ),
    ]
