# Generated by Django 3.2.3 on 2022-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_playlist_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='images',
            field=models.ImageField(blank=True, default=None, max_length=3000, null=True, upload_to='media/playlist_images'),
        ),
    ]
