# Generated by Django 3.2.3 on 2022-06-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
    ]
