# Generated by Django 3.2.3 on 2023-01-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_playlist_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
