# Generated by Django 3.2.3 on 2022-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
