# Generated by Django 3.2.3 on 2023-01-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230107_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/playlist_images'),
        ),
    ]
