# Generated by Django 3.2.3 on 2022-06-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20220604_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
