# Generated by Django 3.2.3 on 2022-06-05 19:09

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rename_user_playlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, upload_to=feed.models.playlistCoverFile, verbose_name='Image'),
        ),
    ]
