# Generated by Django 3.2.3 on 2023-01-08 04:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_playlist_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, default=None, null=True, upload_to='media/playlist_images'), default=None, size=None),
        ),
    ]
