# Generated by Django 3.2.3 on 2023-01-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_playlist_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='images',
        ),
        migrations.CreateModel(
            name='PlaylistImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/playlist_images')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_images', to='feed.playlist')),
            ],
        ),
    ]
