# Generated by Django 4.1.6 on 2023-02-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20230107_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('artist', models.CharField(default='', max_length=300)),
                ('album', models.CharField(default='', max_length=300)),
                ('track_id', models.CharField(default='', max_length=300)),
                ('uri', models.CharField(default='', max_length=300)),
                ('images', models.CharField(default='', max_length=700)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.playlist')),
            ],
        ),
    ]
