# Generated by Django 4.1.6 on 2023-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_playlisttracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistimages',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='playlist_images/'),
        ),
    ]
