# Generated by Django 4.1.6 on 2023-04-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_alter_playlistimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistimages',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
