# Generated by Django 4.1.6 on 2023-04-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_playlistimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistimages',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=None),
        ),
    ]
