# Generated by Django 3.2.3 on 2022-06-05 19:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.aviFile, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.headerFile, verbose_name='Image'),
        ),
    ]
