# Generated by Django 3.2.3 on 2022-12-17 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221018_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='date_followed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
