# Generated by Django 3.2.3 on 2022-06-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220605_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='user_id',
        ),
    ]
