# Generated by Django 3.2.3 on 2022-12-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_date_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_id',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=''),
        ),
    ]
