# Generated by Django 3.2.3 on 2022-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221230_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_id',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='media/avi_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='media/header_images'),
        ),
    ]
