# Generated by Django 3.2.3 on 2022-06-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220608_1528'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_followers',
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='unique_followers'),
        ),
    ]
