# Generated by Django 3.2.3 on 2022-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221230_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='media/avi_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
