# Generated by Django 4.1.6 on 2023-02-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230111_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, default='', max_length=4000, null=True, upload_to='media/avi_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, default='', max_length=4000, null=True, upload_to='media/header_images'),
        ),
    ]
