# Generated by Django 4.1.6 on 2023-02-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avi_pic_alter_user_header_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, default='media/avi_images/defualt_image.png', max_length=4000, null=True, upload_to='media/avi_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, default='media/avi_images/defualt_image.png', max_length=4000, null=True, upload_to='media/header_images'),
        ),
    ]
