# Generated by Django 4.1.6 on 2023-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avi_pic_alter_user_header_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avi_pic',
            field=models.ImageField(blank=True, default='avi_images/defualt_image.png', max_length=4000, null=True, upload_to='avi_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, default='avi_images/defualt_image.png', max_length=4000, null=True, upload_to='header_images/'),
        ),
    ]
