# Generated by Django 4.1.6 on 2023-05-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_avi_pic_alter_user_header_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
