# Generated by Django 4.1.6 on 2023-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_url',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
